export const monthsMapping = {
  janvier: "january",
  février: "february",
  fevrier: "february",
  mars: "march",
  avril: "april",
  mai: "may",
  juin: "june",
  juillet: "july",
  août: "august",
  aout: "august",
  septembre: "september",
  octobre: "october",
  novembre: "november",
  décembre: "december",
  decembre: "december",
};

export const monthMappingNum = {
  "01": "january",
  "02": "february",
  "03": "march",
  "04": "april",
  "05": "may",
  "06": "june",
  "07": "july",
  "08": "august",
  "09": "september",
  "10": "october",
  "11": "november",
  "12": "december",
};
